import './style.css';
import '@fontsource/barlow/latin-400.css';
import '@fontsource/barlow/latin-500.css';
import '@fontsource/barlow/latin-600.css';
import '@fontsource/barlow/latin-700.css';
import '@fontsource/barlow-condensed/latin-500.css';
import '@fontsource/barlow-condensed/latin-600.css';
import { FlightScene } from './scene.js';
import { VEHICLES, makeStages, sample, clockText, engineCount, clamp, mix } from './mission.js';
import { FlightAudio } from './audio.js';
import { REFERENCES, REFERENCE_DATE, referenceContent } from './references.js';
import { broadcastMarkup, renderBroadcast } from './broadcast.js';

const icons={
  play:'<path d="m8 5 11 7-11 7Z" fill="currentColor" stroke="none"/>',pause:'<path d="M8 5v14M16 5v14" stroke-width="4"/>',next:'<path d="m5 6 9 6-9 6Z"/><path d="M18 6v12"/>',prev:'<path d="m19 6-9 6 9 6Z"/><path d="M6 6v12"/>',reset:'<path d="M3 10a9 9 0 1 1 2 8M3 4v6h6"/>',sound:'<path d="m11 4-6 5H2v6h3l6 5ZM16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',mute:'<path d="m11 4-6 5H2v6h3l6 5ZM16 9l6 6m0-6-6 6"/>',full:'<path d="M3 9V3h6m6 0h6v6M3 15v6h6m6 0h6v-6"/>',camera:'<path d="M3 7h5l2-3h4l2 3h5v13H3Z"/><circle cx="12" cy="13" r="4"/>',land:'<path d="m2 17 5-6 4 4 5-9 6 11M2 21h20"/><circle cx="6" cy="5" r="2"/>',ship:'<path d="M3 13h18l-3 6H7ZM8 13V7h8v6m-4-6V3M2 22q3-4 6 0 3-4 6 0 3-4 8 0"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',moon:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',cloud:'<path d="M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13 2 4 4 0 1 1 1 8Z"/>',wind:'<path d="M2 8h13a3 3 0 1 0-3-3M2 12h18a2 2 0 1 1-2 2M2 16h8a3 3 0 1 1-3 3"/>',chevron:'<path d="m9 6 6 6-6 6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-11v2"/>',check:'<path d="m5 12 4 4L20 5"/>',orbit:'<ellipse cx="12" cy="12" rx="11" ry="5" transform="rotate(-30 12 12)"/><circle cx="12" cy="12" r="4"/>',rocket:'<path d="M12 2c6 5 7 11 4 16H8C5 13 6 7 12 2Zm-5 9-4 7h5m9-7 4 7h-5M9 21h6"/><circle cx="12" cy="9" r="2"/>',spark:'<path d="m12 2 2.7 7.3L22 12l-7.3 2.7L12 22l-2.7-7.3L2 12l7.3-2.7Z"/>',path:'<path d="M3 20C3 2 21 2 21 17" stroke-dasharray="3 3"/><circle cx="3" cy="20" r="2"/><circle cx="21" cy="18" r="2"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',flag:'<path d="M5 22V3m0 0q4-4 8 0t7 0v11q-4 4-7 0t-8 0"/>',star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',tower:'<path d="M4 22V2h7v20M4 6h7M4 12h7m0 2h11m-4-7v15M14 9h8"/>'
};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.rocket}</svg>`;
const rocketSVG=type=>`<svg viewBox="0 0 64 90" class="rocket-mini" aria-hidden="true"><defs><linearGradient id="${type}metal"><stop stop-color="#8d9ba6"/><stop offset=".5" stop-color="#f2f6f7"/><stop offset="1" stop-color="#677983"/></linearGradient></defs>${type==='heavy'?'<path d="M17 20q-6 7-5 15v42h10V35q1-8-5-15m30 0q-6 7-5 15v42h10V35q1-8-5-15" fill="#bfcad0"/><path d="M12 71h10v5H12m30-5h10v5H42" fill="#394a57"/>':''}${type==='starship'?`<path d="M32 3q10 9 10 22v54H22V25Q22 12 32 3" fill="url(#${type}metal)"/><path d="M32 3q10 9 10 22v19h-7V13Z" fill="#33434e"/><path d="m22 23-6 7v8l6-3m20-12 6 7v8l-6-3M22 51l-8 9v10l8-4m20-15 8 9v10l-8-4" fill="#8fa1aa"/><path d="M22 45h20M22 50h20M22 55h20M22 60h20M22 65h20M22 70h20" stroke="#687c87" stroke-width=".7"/>`:`<path d="M32 5q8 9 8 18v13l-3 4v38H27V40l-3-4V23q0-9 8-18" fill="url(#${type}metal)"/><path d="M27 38h10v9H27m0 27h10v4H27" fill="#243540"/><path d="M30 52v14" stroke="#526874" stroke-width="1.5"/>`}<path d="m27 81 5 7 5-7" fill="#74d6bf" opacity=".8"/></svg>`;
let saved={};try{saved=JSON.parse(localStorage.getItem('flightlab-prefs')||'{}');}catch{}
const state={vehicle:VEHICLES[saved.vehicle]?saved.vehicle:'falcon9',recovery:saved.recovery==='ocean'?'ocean':'land',weather:['clear','cloudy','windy'].includes(saved.weather)?saved.weather:'clear',night:!!saved.night,kid:!!saved.kid,sound:false,voice:true,broadcast:false,time:0,playing:false,speed:1,manual:false,camera:'cinema',focus:'booster',trajectory:false,justSeek:true,completed:false};
state.stages=makeStages(state.vehicle);
document.querySelector('#app').innerHTML=`
  <header class="topbar">
    <a class="brand" href="#" aria-label="SpaceX Flight Lab 首页"><img class="spacex-logo" src="./reference/spacex-logo.svg" width="147" height="19" alt="SpaceX"/><span class="brand-divider"></span><span class="lab-word">FLIGHT LAB<span>飞行实验室</span></span></a>
    <nav class="main-nav" aria-label="主导航"><span class="active">任务控制<span class="nav-dot"></span></span><button id="guide">飞行手册 ${icon('arrow')}</button><button data-reference-open>官网对照 ${icon('arrow')}</button><a href="./model-review.html" target="_blank" rel="noopener" class="model-review-link">模型检视 ↗</a></nav>
    <div class="header-actions"><span class="local-badge"><i></i> ALL SYSTEMS GO</span><button class="broadcast-toggle" id="broadcast" aria-pressed="false" title="切换直播视图（B）">直播视图</button><button class="kid-button" id="kid" aria-pressed="false">${icon('spark')} 小小指挥官</button><button class="icon-button" id="about" title="关于模拟器" aria-label="关于模拟器">${icon('info')}</button></div>
  </header>
  <main class="flight-deck">
    <div id="scene"></div><div class="scene-vignette"></div>
    <aside class="mission-panel glass">
      <div class="section-heading"><div><span class="eyebrow">MISSION CONFIGURATION</span><h2>选择你的火箭</h2></div><span class="tiny-index">01 — 03</span></div>
      <div class="vehicle-list" role="group" aria-label="选择火箭">${Object.entries(VEHICLES).map(([key,v])=>`<button class="vehicle-card" data-vehicle="${key}" aria-pressed="false"><span class="mini-wrap">${rocketSVG(key)}</span><span class="vehicle-text"><strong>${v.name}</strong><span>${v.chinese}</span></span><span class="selection-mark">${icon('check')}</span></button>`).join('')}</div>
      <div class="spec-grid"><div><span>箭体高度</span><strong id="spec-height"></strong></div><div><span>起飞推力</span><strong id="spec-thrust"></strong></div><div><span>发动机</span><strong id="spec-engines"></strong></div></div>
      <div class="panel-rule"></div>
      <div class="section-label"><h3>回收目的地</h3><span>RECOVERY</span></div>
      <div class="recovery-options" role="group" aria-label="回收目的地"><button data-recovery="land" aria-pressed="true">${icon('land')}<strong id="land-label">陆地着陆场</strong><span id="land-sub">LANDING ZONE</span></button><button data-recovery="ocean" aria-pressed="false">${icon('ship')}<strong id="ocean-label">海上回收船</strong><span id="ocean-sub">DRONESHIP</span></button></div>
      <div class="environment-section"><div class="section-label"><h3>大气环境</h3><button id="night" title="切换昼夜" aria-label="切换昼夜" aria-pressed="false">${icon('sun')} <span>日间</span></button></div>
      <div class="weather-options" role="group" aria-label="大气环境"><button data-weather="clear">${icon('sun')}晴空</button><button data-weather="cloudy">${icon('cloud')}多云</button><button data-weather="windy">${icon('wind')}海风</button></div></div>
      <div class="mission-footnote"><i></i><span id="mission-location">LC–39A · KENNEDY SPACE CENTER</span></div>
    </aside>
    <div class="scene-top"><div class="broadcast-label"><span class="live-dot"></span> LIVE SIMULATION <span class="broadcast-divider">/</span> <span id="view-label">TRACKING CAM 01</span></div><h1 id="vehicle-title">FALCON 9</h1><p id="mission-tagline">让回收成为日常</p></div>
    <div class="view-toolbar"><div class="camera-options" role="group" aria-label="镜头选择"><button data-camera="cinema" title="电影跟随镜头" aria-pressed="true">${icon('camera')}<span>跟随</span></button><button data-camera="wide" title="全景镜头">${icon('orbit')}<span>全景</span></button><button data-camera="onboard" title="箭载镜头">${icon('rocket')}<span>箭载</span></button><button data-camera="landing" title="回收特写">${icon('flag')}<span>回收</span></button></div><button class="icon-button path-button" id="trajectory" title="显示或隐藏飞行轨迹" aria-label="显示飞行轨迹" aria-pressed="false">${icon('path')}</button></div>
    <div class="focus-switch" role="group" aria-label="跟踪目标"><span>跟踪目标</span><button data-focus="booster" aria-pressed="true">一级助推器</button><button data-focus="upper" aria-pressed="false">二级 / 飞船</button></div>
    <div class="countdown-display" id="countdown" hidden><span>PREPARE FOR LIFTOFF</span><strong>10</strong><p>准备好，去触摸天空</p></div>
    <div class="child-caption" id="child-caption" hidden><span>${icon('spark')} 给小小指挥官</span><p></p></div>
    <aside class="telemetry-panel glass">
      <div class="telemetry-heading"><span class="eyebrow">FLIGHT TELEMETRY</span><span class="data-live"><i></i>实时</span></div>
      <div class="mission-clock" id="mission-clock">T−00:00:10</div><div class="clock-caption">任务计时 <span id="flight-status">等待发射</span></div>
      <div class="telemetry-metric"><div class="metric-top"><span>高度 <small>ALTITUDE</small></span>${icon('arrow','up-arrow')}</div><div class="metric-value"><strong id="altitude">0.0</strong><span>km</span></div><svg class="sparkline" viewBox="0 0 200 30" preserveAspectRatio="none" aria-hidden="true"><path class="graph-grid" d="M0 29h200M0 14h200"/><path id="altitude-chart" d="M0 28h200"/></svg></div>
      <div class="telemetry-metric velocity"><div class="metric-top"><span>速度 <small>VELOCITY</small></span><span class="unit-dot"></span></div><div class="metric-value"><strong id="velocity">0</strong><span>km/h</span></div><svg class="sparkline" viewBox="0 0 200 30" preserveAspectRatio="none" aria-hidden="true"><path class="graph-grid" d="M0 29h200M0 14h200"/><path id="velocity-chart" d="M0 28h200"/></svg></div>
      <div class="panel-rule"></div><div class="section-label"><h3>发动机状态</h3><span id="engine-type">MERLIN 1D</span></div>
      <div class="engine-block"><svg id="engine-map" viewBox="0 0 130 100" role="img" aria-label="发动机工作状态图"></svg><div class="engine-readout"><div><strong id="engine-active">0</strong><span id="engine-total">/ 9</span></div><span id="engine-status">STANDBY</span><small><i></i> 工作中 <i class="off"></i> 关闭</small></div></div>
      <div class="attitude-row"><div class="attitude-ball"><div class="horizon" id="horizon"><div class="horizon-line"></div><span>− − − −</span></div><div class="reticle"></div></div><div><span>姿态角 <small>PITCH</small></span><strong id="pitch">90.0°</strong></div><div class="vertical-stat"><span>垂直速度</span><strong id="vertical-speed">0 <small>m/s</small></strong></div></div>
      <div class="atmosphere-data"><span>气压 <b id="pressure">1013</b> hPa</span><span>风速 <b id="wind">3.2</b> m/s</span></div>
    </aside>
    <div class="scene-bottom"><div class="phase-caption"><span class="phase-number" id="phase-number">01</span><div><div class="phase-name"><h2 id="phase-title">点火倒计时</h2><span id="phase-en">COUNTDOWN</span></div><p id="phase-description"></p></div></div><span class="orbit-hint">拖动旋转视角 <i>·</i> 滚轮缩放</span></div>
    <div class="recovery-badge" id="recovery-badge" hidden>${icon('check')}<div><strong>欢迎回家</strong><span>THE BOOSTER HAS LANDED</span></div></div>
    ${broadcastMarkup()}
    <div id="loading"><div class="loader-orbit">${icon('rocket')}</div><h2>正在准备你的发射任务</h2><p>下一站，星辰大海。</p></div>
  </main>
  <footer class="mission-console">
    <div class="timeline-header"><div><strong>飞行计划</strong><span>FLIGHT PLAN</span><small>点选阶段，接管飞行</small></div><div class="mode-switch"><button data-mode="auto" aria-pressed="true">自动演示</button><button data-mode="manual" aria-pressed="false">手动分阶段</button></div></div>
    <div class="timeline-scroll"><div id="timeline" class="timeline"></div></div>
    <div class="playback-bar"><button id="launch" class="launch-button">${icon('play')}<span>启动发射</span></button><div class="step-controls"><button class="icon-button" id="previous" title="上一阶段（←）" aria-label="上一阶段">${icon('prev')}</button><button class="icon-button" id="next" title="下一阶段（→）" aria-label="下一阶段">${icon('next')}</button></div><span class="control-divider"></span><label class="speed-label" for="speed">播放速度</label><select id="speed" aria-label="播放速度"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option></select><div class="seek-wrap"><input id="seek" type="range" min="0" max="140" step="0.05" value="0" aria-label="任务播放进度"/><span id="playback-time">00:00 <i>/ 02:23</i></span></div><div class="utility-controls"><button class="icon-button" id="reset" title="重新开始（R）" aria-label="重新开始">${icon('reset')}</button><button class="icon-button" id="sound" title="开启声音（M）" aria-label="开启声音" aria-pressed="false">${icon('mute')}</button><button class="icon-button" id="capture" title="保存三维画面" aria-label="保存三维画面">${icon('camera')}</button><button class="icon-button" id="fullscreen" title="全屏（F）" aria-label="全屏">${icon('full')}</button></div></div>
    <div class="console-bottom"><span><i></i> 为每一个仰望星空的小朋友而造</span><span>3D EDUCATIONAL SIMULATION <b>·</b> 非 SpaceX 官方产品</span></div>
  </footer>
  <div class="toast" id="toast" role="status"></div>
  <dialog id="guide-dialog"><button class="dialog-close icon-button" data-close aria-label="关闭飞行手册">${icon('close')}</button><span class="eyebrow">A LITTLE GUIDE TO A BIG ADVENTURE</span><h2>你好，小小任务指挥官。</h2><p class="dialog-intro">选一枚喜欢的火箭，按下「启动发射」。剩下的，就交给好奇心。</p><div class="guide-grid"><section>${icon('rocket')}<h3>指挥发射</h3><p>自动演示会完成整趟旅程。切换「手动分阶段」，每一阶段结束后会暂停，按下一阶段继续。</p></section><section>${icon('camera')}<h3>找到最棒的角度</h3><p>拖动画面旋转，滚轮或双指缩放。打开「直播视图」让画面更大，也可以试试箭载镜头。</p></section><section>${icon('flag')}<h3>接火箭回家</h3><p>猎鹰系列可选择陆地或海上回收船。猎鹰重型回收段跟随两枚侧助推器；中心芯级继续向远处飞行。</p></section><section>${icon('spark')}<h3>一起听故事</h3><p>打开「小小指挥官」和声音，听每个阶段的小讲解。语音使用浏览器提供的中文语音，离线可用性取决于系统。</p></section></div><div class="keyboard-guide"><kbd>Space</kbd> 播放 / 暂停 <kbd>← →</kbd> 切换阶段 <kbd>R</kbd> 重新开始 <kbd>F</kbd> 全屏 <kbd>B</kbd> 直播视图</div><button class="dialog-primary" data-close>准备好了，出发 ${icon('arrow')}</button></dialog>
  <dialog id="about-dialog"><button class="dialog-close icon-button" data-close aria-label="关闭关于">${icon('close')}</button><span class="eyebrow">BUILT FOR WONDER</span><h2>给仰望星空的你。</h2><p class="dialog-intro">用一次看得见、摸得着的飞行，把航天的浪漫带给小朋友。</p><p>火箭按公开外形与尺寸比例程序化建模，包含猎鹰系列的九机布局、栅格舵与着陆腿，以及星舰的 33 台助推器发动机、热分级环、隔热瓦和四片襟翼。外形参考构型为 Falcon 9 Block 5、Falcon Heavy 与官网 124 米参考构型的星舰组合体（助推器 72 米、飞船 52 米）。星舰沿用 124 米参考构型，不混用官网 V3 更新中的硬件尺寸。页头使用官网 SVG 字标，猎鹰涂装和结构对照官方渲染图调整。</p><p>这是科普演示：飞行时间经过压缩，遥测值、轨迹、气动与海况为示意数据，不是工程级物理仿真，也不是实际直播。风和云主要影响场景表现。任意阶段都可跳转，分离和回收动作按预设轨迹重现。</p><p>星舰的陆地回收演示为超级重型助推器塔架捕获，海面模式为受控溅落，飞船始终演示海面溅落。猎鹰重型可选的双船回收为教学场景；其中心芯级不在本演示回收范围内。飞船再入段会明确快进任务时间。</p><div class="source-links"><a href="./model-review.html" target="_blank" rel="noopener">模型检视 · 旋转看细节 ↗</a><a href="https://www.spacex.com/vehicles/falcon-9/" target="_blank" rel="noreferrer">Falcon 9 ${icon('arrow')}</a><a href="https://www.spacex.com/vehicles/falcon-heavy/" target="_blank" rel="noreferrer">Falcon Heavy ${icon('arrow')}</a><a href="https://www.spacex.com/vehicles/starship/" target="_blank" rel="noreferrer">Starship ${icon('arrow')}</a></div><button class="dialog-primary" data-reference-open>官网对照 · 看真实火箭 ↗</button><p class="unofficial">独立制作的教育体验，与 SpaceX 无隶属关系。官方图片与标识的权利归 SpaceX。</p></dialog>
  <dialog id="success-dialog" class="success-dialog"><button class="dialog-close icon-button" data-close aria-label="关闭任务完成">${icon('close')}</button><div class="mission-patch">${icon('rocket')}<span>JUNIOR FLIGHT COMMANDER</span><div>★ ★ ★</div></div><span class="eyebrow">MISSION ACCOMPLISHED</span><h2>任务成功，指挥官！</h2><p>从出发，到回家。<br>宇宙很大，你的好奇心更大。</p><button class="dialog-primary" id="fly-again">再飞一次 ${icon('rocket')}</button><button class="text-button" data-close>再看看我的火箭</button></dialog>
  <dialog id="reference-dialog" aria-labelledby="reference-title"><button class="dialog-close icon-button" data-close aria-label="关闭官网对照">${icon('close')}</button><span class="eyebrow">FROM THE REAL WORLD</span><h2 id="reference-title">去看看真实的火箭。</h2><p class="dialog-intro">对照 SpaceX 的官方图片，认识模型里的每一个细节。</p><div class="reference-tabs" role="group" aria-label="选择官网参考火箭">${Object.entries(REFERENCES).map(([key,r])=>`<button data-reference="${key}" aria-pressed="false">${r.chinese}</button>`).join('')}</div><div id="reference-content"></div><div class="reference-credit"><img src="./reference/spacex-logo.svg" width="147" height="19" alt="SpaceX 官方字标"/><p>页头采用官网 SVG 字标；照片与渲染参考图来自 SpaceX，图片权利归原权利人。三维模型、场景和动画由本项目制作，细节按公开资料近似重建。规格核对日期：${REFERENCE_DATE}。</p></div></dialog>
`;

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const audio=new FlightAudio();let scene,frame=0,lastStage=-1,lastCount=null,lastUI=0,lastNow=performance.now(),wall=0,lastInfo={angle:0},engineLayoutKey='';
function persist(){try{localStorage.setItem('flightlab-prefs',JSON.stringify({vehicle:state.vehicle,recovery:state.recovery,weather:state.weather,night:state.night,kid:state.kid}));}catch{}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3000);}
function prettyTime(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
function renderConfig(){const v=VEHICLES[state.vehicle];$$('[data-vehicle]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.vehicle===state.vehicle));$('#vehicle-title').textContent=v.name;$('#mission-tagline').textContent=v.subtitle;$('#spec-height').textContent=v.height;$('#spec-thrust').textContent=v.thrust;$('#spec-engines').textContent=`${v.engines} 台`;$('#engine-type').textContent=v.engine;$('#mission-location').textContent=`${v.pad} · ${v.site}`;
  const star=state.vehicle==='starship';$('#land-label').textContent=star?'塔架捕获':'陆地着陆场';$('#land-sub').textContent=star?'TOWER CATCH':'LANDING ZONE';$('#ocean-label').textContent=star?'海面溅落':'海上回收船';$('#ocean-sub').textContent=star?'SOFT SPLASHDOWN':'DRONESHIP';
  $$('[data-recovery]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.recovery===state.recovery));$$('[data-weather]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.weather===state.weather));$('#night').innerHTML=icon(state.night?'moon':'sun')+` <span>${state.night?'夜间':'日间'}</span>`;$('#night').setAttribute('aria-pressed',state.night);
  document.body.classList.toggle('kid-mode',state.kid);$('#kid').setAttribute('aria-pressed',state.kid);$('#child-caption').hidden=!state.kid;
  $('#timeline').innerHTML=state.stages.map((s,i)=>`<button class="timeline-stage" data-stage="${i}" title="${s.title} · ${s.en}" aria-label="跳转到${s.title}"><span class="stage-dot">${s.id==='touchdown'||s.id==='splash'?icon('check'):`<span>${String(i+1).padStart(2,'0')}</span>`}</span><span class="stage-label">${s.title}</span></button>`).join('');$('#timeline').style.setProperty('--stage-count',state.stages.length);$('#seek').max=state.stages.at(-1).end;
  $('#timeline').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>goToStage(Number(b.dataset.stage),false)));
  renderEngines();persist();
}
function renderEngines(upper=false){let pts=[];const type=upper?state.vehicle==='starship'?'ship':'vacuum':state.vehicle;engineLayoutKey=state.vehicle+(upper?':upper':':booster');
  function cluster(cx,cy,r){const a=[[cx,cy]];for(let i=0;i<8;i++)a.push([cx+Math.sin(i*Math.PI/4)*r,cy+Math.cos(i*Math.PI/4)*r]);return a;}
  if(type==='ship'){for(const[n,r,offset]of[[3,11,0],[3,30,.5]])for(let i=0;i<n;i++)pts.push([65+Math.sin((i+offset)*2*Math.PI/n)*r,50+Math.cos((i+offset)*2*Math.PI/n)*r]);}
  else if(type==='vacuum')pts=[[65,50]];
  else if(type==='heavy'){pts=[...cluster(24,50,12),...cluster(65,50,12),...cluster(106,50,12)];}
  else if(type==='starship'){for(const[n,r]of[[3,8],[10,21],[20,37]])for(let i=0;i<n;i++)pts.push([65+Math.sin(i*2*Math.PI/n)*r,50+Math.cos(i*2*Math.PI/n)*r]);}
  else pts=cluster(57,50,27);
  const r=type==='heavy'?3.5:type==='starship'?3.7:7.3;
  $('#engine-map').innerHTML=`<circle class="engine-outline" cx="${type==='falcon9'?57:65}" cy="50" r="44"/>${pts.map(([x,y],i)=>`<circle class="engine-cell" data-engine="${i}" cx="${x}" cy="${y}" r="${type==='ship'?(i<3?5.1:9):r}"><title>${type==='ship'?(i<3?'Raptor 海平面型 · Ø 1.3 m':'Raptor Vacuum · Ø 2.3 m'):`发动机 ${i+1}`}</title></circle>`).join('')}`;
}
function reset(){state.time=0;state.playing=false;state.manualPending=false;state.completed=false;state.justSeek=true;state.focus='booster';state.camera='cinema';lastStage=-1;lastCount=null;clearTimeout(toast.timer);$('#toast').classList.remove('visible');audio.speak('');scene?.resetCamera();syncView();renderUI(true);}
function goToStage(index,play=state.playing){index=clamp(index,0,state.stages.length-1);state.time=state.stages[index].start;state.manualPending=false;state.playing=play;state.justSeek=true;state.completed=false;lastStage=-1;$('#success-dialog').close();renderUI(true);}
function togglePlay(){if(state.completed||state.time>=state.stages.at(-1).end)reset();if(state.manualPending){goToStage(sample(state.stages,state.time).index+1,false);}state.playing=!state.playing;if(state.sound)audio.init();if(!state.playing)window.speechSynthesis?.cancel();else if(state.kid)audio.speak(sample(state.stages,state.time).child);renderUI(true);}
function syncView(){$$('[data-camera]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.camera===state.camera));$$('[data-focus]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.focus===state.focus));$('#view-label').textContent={cinema:'TRACKING CAM 01',wide:'WIDE ANGLE CAM',onboard:'ONBOARD CAMERA',landing:'LANDING CAM 02'}[state.camera];}
function updateGraph(selector,key,max){const path=[];for(let i=0;i<=40;i++){const t=Math.max(0,state.time-35)+Math.min(35,state.time)*i/40;const val=sample(state.stages,t)[key];path.push(`${i===0?'M':'L'}${i*5},${28-clamp(val/max)*26}`);}$(selector).setAttribute('d',path.join(' '));}
function renderUI(force=false){
  const s=sample(state.stages,state.time),v=VEHICLES[state.vehicle];const star=state.vehicle==='starship';let alt=s.altitude,vel=s.velocity;
  const upperFocused=state.focus==='upper'&&state.time>=state.stages.find(s=>s.id==='separation').start&&!['shipentry','belly','flip','splash'].includes(s.id);
  if(upperFocused){const separation=state.stages.find(s=>s.id==='separation');const elapsed=state.time-separation.start;alt=lastInfo.activePart==='upper'?lastInfo.altitude:separation.a0;vel=mix(separation.v0,27300,clamp(elapsed/100));}
  $('#mission-clock').textContent=clockText(s.missionTime);$('#altitude').textContent=alt<100?alt.toFixed(1):Math.round(alt).toLocaleString('en-US');$('#velocity').textContent=Math.round(vel).toLocaleString('en-US');
  $('#flight-status').textContent=state.completed?'任务完成':state.playing?'飞行中':state.time===0?'等待发射':state.manual?'等待指令':'已暂停';$('#flight-status').classList.toggle('running',state.playing);
  $('#pitch').textContent=`${(90-Math.abs((lastInfo.angle||0)*180/Math.PI)).toFixed(1)}°`;
  $('#horizon').style.transform=`rotate(${-(lastInfo.angle||0)*180/Math.PI}deg)`;
  const descending=['coast','entry','landing','shipentry','belly','flip'].includes(s.id);$('#vertical-speed').innerHTML=`${descending?'−':''}${Math.round(vel/3.6*Math.abs(Math.cos(lastInfo.angle||0)))} <small>m/s</small>`;
  $('#pressure').textContent=(1013.25*Math.exp(-alt/7.5)).toFixed(alt>40?2:0);$('#wind').textContent=(state.weather==='windy'?12.4:state.weather==='cloudy'?5.8:3.2).toFixed(1);
  let engines=upperFocused?(state.time-state.stages.find(s=>s.id==='separation').start<100?(star?6:1):0):engineCount(state.vehicle,s.id,s.progress);if(['shipentry','belly','flip','splash'].includes(s.id))engines=s.id==='flip'?3:0;
  const showUpper=upperFocused||['shipentry','belly','flip','splash'].includes(s.id);const layoutKey=state.vehicle+(showUpper?':upper':':booster');if(layoutKey!==engineLayoutKey)renderEngines(showUpper);$('#engine-type').textContent=showUpper?(star?'RAPTOR · SHIP':'MERLIN VACUUM'):v.engine;
  $('#engine-active').textContent=engines;$('#engine-total').textContent=`/ ${upperFocused||['shipentry','belly','flip','splash'].includes(s.id)?star?6:1:v.engines}`;$('#engine-status').textContent=engines?'ENGINES FIRING':'STANDBY';$('#engine-status').classList.toggle('firing',engines>0);
  $$('.engine-cell').forEach((e,i)=>{let on=i<engines;if(state.vehicle==='falcon9'&&engines===3&&!showUpper)on=[0,1,5].includes(i);if(state.vehicle==='heavy'&&!upperFocused){const cluster=Math.floor(i/9),idx=i%9;if(['boostback','entry'].includes(s.id))on=engines>0&&cluster!==1&&[0,1,5].includes(idx);else if(s.id==='landing')on=cluster!==1&&idx===0;else if(s.id==='side')on=cluster===1;else on=engines>0;}e.classList.toggle('on',on);});$('#engine-map').setAttribute('aria-label',`${engines} 台发动机工作中`);
  $('#phase-number').textContent=String(s.index+1).padStart(2,'0');$('#phase-title').textContent=s.title;$('#phase-en').textContent=s.en;$('#phase-description').textContent=upperFocused?'镜头跟随二级继续飞行。可切回「一级助推器」观看返航与着陆。':s.text;$('#child-caption p').textContent=s.child;
  $$('.timeline-stage').forEach((b,i)=>{b.classList.toggle('current',i===s.index);b.classList.toggle('done',i<s.index);b.setAttribute('aria-current',i===s.index?'step':'false');});
  const launchText=state.playing?'暂停飞行':state.completed?'再飞一次':state.manualPending?'继续下一阶段':state.time===0?state.kid?'发射！':'启动发射':state.manual?'开始本阶段':'继续飞行';
  // Keep the clickable contents stable between telemetry updates.
  if($('#launch span').textContent!==launchText)$('#launch').innerHTML=icon(state.playing?'pause':'play')+`<span>${launchText}</span>`;$('#launch').classList.toggle('playing',state.playing);
  $('#previous').disabled=s.index===0;$('#next').disabled=s.index===state.stages.length-1;
  $('#seek').value=state.time;$('#seek').style.setProperty('--progress',`${state.time/s.total*100}%`);$('#playback-time').innerHTML=`${prettyTime(state.time)} <i>/ ${prettyTime(s.total)}</i>`;
  const counting=s.id==='countdown'&&state.playing;$('#countdown').hidden=!counting;if(counting)$('#countdown strong').textContent=Math.max(1,Math.ceil(10*(1-s.progress)));
  $('#recovery-badge').hidden=s.id!=='touchdown'&&s.id!=='splash';
  if(s.id==='touchdown'&&star){$('#recovery-badge strong').textContent=state.recovery==='land'?'捕获成功':'海面溅落成功';}else $('#recovery-badge strong').textContent=s.id==='splash'?'星舰，欢迎回家':'欢迎回家';
  updateGraph('#altitude-chart','altitude',star?110:115);updateGraph('#velocity-chart','velocity',star?27000:8000);
  if(s.index!==lastStage){lastStage=s.index;if(state.playing&&state.kid&&s.id!=='countdown')audio.speak(s.child);if(s.id==='touchdown'||s.id==='splash')audio.chime();if(['shipentry','belly','flip','splash'].includes(s.id)){$('.focus-switch').classList.add('ship-focus');}else $('.focus-switch').classList.remove('ship-focus');}
  if(counting){const n=Math.ceil(10*(1-s.progress));if(n!==lastCount&&n<=5){lastCount=n;audio.speak(String(n));}}
  audio.update(engines,state.playing);
  renderBroadcast(state,s,lastInfo.telemetry);
}

$$('[data-vehicle]').forEach(b=>b.addEventListener('click',()=>{if(state.vehicle===b.dataset.vehicle)return;state.vehicle=b.dataset.vehicle;state.stages=makeStages(state.vehicle);scene?.setVehicle(state.vehicle);renderConfig();reset();}));
$$('[data-recovery]').forEach(b=>b.addEventListener('click',()=>{state.recovery=b.dataset.recovery;state.justSeek=true;renderConfig();toast(state.vehicle==='starship'?(state.recovery==='land'?'助推器将由塔架捕获；飞船仍在海面溅落':'助推器与飞船演示受控海面溅落'):(state.recovery==='land'?'回收目的地：陆地着陆场':'回收目的地：无人回收船'));}));
$$('[data-weather]').forEach(b=>b.addEventListener('click',()=>{state.weather=b.dataset.weather;scene?.setEnvironment(state.weather,state.night);renderConfig();}));
$('#night').addEventListener('click',()=>{state.night=!state.night;scene?.setEnvironment(state.weather,state.night);renderConfig();});
$('#kid').addEventListener('click',()=>{state.kid=!state.kid;renderConfig();renderUI(true);if(state.kid){toast('小小指挥官已就位！开启声音可以听中文讲解');if(state.sound)audio.speak(sample(state.stages,state.time).child);}});
$('#broadcast').addEventListener('click',()=>{state.broadcast=!state.broadcast;document.body.classList.toggle('broadcast-mode',state.broadcast);$('#broadcast').setAttribute('aria-pressed',state.broadcast);$('#broadcast').textContent=state.broadcast?'返回指挥台':'直播视图';state.justSeek=true;});
$$('[data-camera]').forEach(b=>b.addEventListener('click',()=>{state.camera=b.dataset.camera;scene?.setCamera(state.camera);state.justSeek=true;syncView();}));
$$('[data-focus]').forEach(b=>b.addEventListener('click',()=>{state.focus=b.dataset.focus;state.justSeek=true;syncView();if(state.focus==='upper'&&state.time<state.stages.find(s=>s.id==='separation').start)toast('分级后会跟随二级；现在两级还连在一起');}));
$('#trajectory').addEventListener('click',()=>{state.trajectory=!state.trajectory;$('#trajectory').setAttribute('aria-pressed',state.trajectory);});
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.manual=b.dataset.mode==='manual';$$('[data-mode]').forEach(q=>q.setAttribute('aria-pressed',(q.dataset.mode==='manual')===state.manual));toast(state.manual?'每个阶段结束后暂停，等待你的下一条指令':'自动完成所有发射与回收阶段');renderUI(true);}));
$('#launch').addEventListener('click',togglePlay);$('#previous').addEventListener('click',()=>goToStage(sample(state.stages,state.time).index-1,state.manual?false:state.playing));$('#next').addEventListener('click',()=>goToStage(sample(state.stages,state.time).index+1,state.manual?true:state.playing));$('#reset').addEventListener('click',reset);
$('#speed').addEventListener('change',e=>state.speed=Number(e.target.value));$('#seek').addEventListener('input',e=>{state.time=Number(e.target.value);state.justSeek=true;state.manualPending=false;state.completed=false;renderUI(true);});
$('#sound').addEventListener('click',()=>{state.sound=!state.sound;audio.setEnabled(state.sound);$('#sound').innerHTML=icon(state.sound?'sound':'mute');$('#sound').setAttribute('aria-pressed',state.sound);$('#sound').setAttribute('aria-label',state.sound?'关闭声音':'开启声音');$('#sound').title=state.sound?'关闭声音（M）':'开启声音（M）';if(state.sound&&state.kid)audio.speak(sample(state.stages,state.time).child);toast(state.sound?'声音已开启：发动机声与倒数'+(state.kid?'，以及中文讲解':''):'声音已关闭');});
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('当前窗口不支持全屏，可使用浏览器的 F11');}});
$('#capture').addEventListener('click',()=>{if(!scene)return;const a=document.createElement('a');a.href=scene.screenshot();a.download=`${state.vehicle}-${sample(state.stages,state.time).id}.png`;a.click();toast('三维画面已保存，留住这次太空旅行');});
$('#guide').addEventListener('click',()=>$('#guide-dialog').showModal());$('#about').addEventListener('click',()=>$('#about-dialog').showModal());$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
function showReference(type){$('#reference-content').innerHTML=referenceContent(type);$$('[data-reference]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.reference===type));}
$$('[data-reference-open]').forEach(b=>b.addEventListener('click',()=>{$('#about-dialog').close();showReference(state.vehicle);$('#reference-dialog').showModal();$('#reference-dialog').scrollTop=0;}));
$$('[data-reference]').forEach(b=>b.addEventListener('click',()=>showReference(b.dataset.reference)));
$('#fly-again').addEventListener('click',()=>{$('#success-dialog').close();reset();togglePlay();});$('.brand').addEventListener('click',e=>{e.preventDefault();reset();});
document.addEventListener('keydown',e=>{if($('dialog[open]')||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay();}else if(e.key==='ArrowRight'){e.preventDefault();$('#next').click();}else if(e.key==='ArrowLeft'){e.preventDefault();$('#previous').click();}else if(e.key.toLowerCase()==='r')reset();else if(e.key.toLowerCase()==='m')$('#sound').click();else if(e.key.toLowerCase()==='f')$('#fullscreen').click();else if(e.key.toLowerCase()==='b')document.querySelector('#broadcast').click();else if(e.key.toLowerCase()==='k')$('#kid').click();});
renderConfig();syncView();renderUI(true);
try{scene=new FlightScene($('#scene'));scene.setVehicle(state.vehicle);scene.setEnvironment(state.weather,state.night);$('#loading').classList.add('loaded');setTimeout(()=>$('#loading').remove(),700);}catch(error){console.error(error);$('#loading').innerHTML=`<div class="loader-orbit">${icon('info')}</div><h2>三维场景暂时无法启动</h2><p>请使用支持 WebGL 的 Chrome 或 Edge，并开启浏览器硬件加速。</p><button class="dialog-primary" onclick="location.reload()">重新尝试</button>`;}
function animate(now){const dt=Math.min((now-lastNow)/1000,.07);lastNow=now;wall+=dt;
  if(state.playing){const before=sample(state.stages,state.time);state.time=Math.min(state.time+dt*state.speed,state.stages.at(-1).end);
    if(state.manual&&state.time>=before.end&&before.index<state.stages.length-1){state.time=before.end-.001;state.playing=false;state.manualPending=true;toast('本阶段完成，等待你的指令。点击「继续下一阶段」');}
    if(state.time>=state.stages.at(-1).end){state.playing=false;state.completed=true;if(!$('#success-dialog').open)$('#success-dialog').showModal();audio.chime();}
  }
  const s=sample(state.stages,state.time);if(scene){lastInfo=scene.update(s,state,dt,wall);state.justSeek=false;}
  if(now-lastUI>90){renderUI();lastUI=now;}frame=requestAnimationFrame(animate);
}
requestAnimationFrame(animate);
// Read-only inspection API for checking a running build without changing the simulation.
window.flightLab={getState:()=>({vehicle:state.vehicle,recovery:state.recovery,time:state.time,playing:state.playing,manual:state.manual,camera:state.camera,focus:state.focus,phase:sample(state.stages,state.time).id,stages:state.stages.map(s=>({id:s.id,start:s.start,end:s.end})),total:state.stages.at(-1).end,renderer:scene?{calls:scene.renderer.info.render.calls,geometries:scene.renderer.info.memory.geometries,textures:scene.renderer.info.memory.textures}:null})};
window.flightLab.getVisualState=()=>scene?{booster:[scene.vehicle.booster,...scene.vehicle.sides].map(p=>({engines:p.engines.filter(e=>e.flame.visible).length,position:p.group.position.toArray(),legAngle:p.legs[0]?.rotation.x||0,feet:p.legs.map(l=>l.userData.foot.getWorldPosition(p.group.position.clone()).toArray())})),upper:{engines:scene.vehicle.upper.engines.filter(e=>e.flame.visible).length,position:scene.vehicle.upper.group.position.toArray(),heatshieldNormal:scene.vehicle.upper.group.position.clone().set(0,0,1).applyQuaternion(scene.vehicle.upper.group.quaternion).toArray(),axis:scene.vehicle.upper.group.position.clone().set(0,1,0).applyQuaternion(scene.vehicle.upper.group.quaternion).toArray()},telemetry:lastInfo.telemetry,launchAltitude:scene.launchAltitude,modelHeight:scene.vehicle.height}:null;
window.flightLab.inspectRendering=()=>{if(!scene)return null;const parts=scene.type==='heavy'?scene.vehicle.sides:[scene.vehicle.booster];return{
  depth:scene.renderer.capabilities.reversedDepthBuffer?'reverse-float':'logarithmic',samples:scene.composer.renderTarget1.samples,
  separateBackground:scene.world.earth.parent===scene.world.background&&scene.world.background!==scene.scene,
  groundFade:scene.world.landMat.uniforms.fade.value,groundDepthWrites:[...scene.world.groundMaterials,scene.world.landMat,scene.world.waterMat].every(m=>m.depthWrite),
  cameraPosition:scene.camera.position.toArray(),cameraQuaternion:scene.camera.quaternion.toArray(),
  contacts:parts.map((p,i)=>{const platform=i===0?scene.barge:scene.barge2;return p.legs.map(l=>{const point=l.userData.foot.localToWorld(p.group.position.clone().set(0,-.09,0));return state.recovery==='ocean'?platform.worldToLocal(point).y-.17:point.y-.57;});})
};};



