import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { createVehicle, disposeVehicle, setLandingLegs, setShipFlaps } from './models.js';
import { dimensionSummary, dimensionContent } from './dimensions.js';
import { createStableRenderer, prepareSceneDepth } from './rendering.js';
import './model-review.css';

document.getElementById('review-app').innerHTML=`<header><a href="./index.html"><img src="./reference/spacex-logo.svg" alt="SpaceX"><span>FLIGHT LAB</span></a><span>模型检视</span><a class="return" href="./index.html">返回发射模拟器 ↗</a></header><main><aside><span class="eyebrow">LOOK A LITTLE CLOSER</span><h1>每个细节，<br>都值得看清。</h1><div class="vehicle-picks"><button data-model="ship" aria-pressed="true">星舰飞船 <span>STARSHIP · 52 m</span></button><button data-model="falcon9" aria-pressed="false">猎鹰 9 号一级 <span>FALCON 9 · BLOCK 5</span></button><button data-model="heavy" aria-pressed="false">猎鹰重型 <span>FALCON HEAVY · 70 m</span></button><button data-model="booster" aria-pressed="false">超级重型助推器 <span>SUPER HEAVY · 72 m</span></button></div><div class="mechanism"><label for="deploy">机构展开 <strong id="deploy-value">0%</strong></label><input id="deploy" type="range" min="0" max="1" step=".01" value="0"><p id="mechanism-note">转动四片襟翼，观察铰链与两侧表面。</p></div><div class="notes" id="model-notes"></div><p class="boundary">按 SpaceX 官网尺寸与公开照片重建。襟翼外伸尺寸、支腿机构和瓦片排布仍为近似，非官方 CAD。</p><a class="source" href="https://www.spacex.com/vehicles/starship" target="_blank" rel="noreferrer" id="official-link">查看官方参考 ↗</a></aside><section class="viewer"><div id="model-canvas"></div><div class="viewer-heading"><span class="eyebrow">3D MODEL INSPECTION</span><h2 id="model-title">STARSHIP</h2></div><div class="view-picks"><button data-view="front">迎风面 / 正面</button><button data-view="back">背面</button><button data-view="detail">机构近看</button><button data-view="engines">发动机</button><button data-view="overall">整体</button></div><div class="hint">拖动旋转 · 滚轮 / 双指缩放 <span id="view-caption">黑色隔热瓦朝向迎风面，背风面露出不锈钢。</span></div></section></main>`;
document.querySelector('.mechanism').insertAdjacentHTML('afterend','<section class="dimension-summary" id="dimension-summary" aria-label="当前型号外形尺寸"></section>');
document.body.insertAdjacentHTML('beforeend','<dialog id="dimensions-dialog" aria-labelledby="dimensions-title"><button type="button" class="dimensions-close" aria-label="关闭外形尺寸">×</button><div id="dimensions-content"></div></dialog>');
const dimensionDialog=document.getElementById('dimensions-dialog');
dimensionDialog.querySelector('.dimensions-close').addEventListener('click',()=>dimensionDialog.close());
dimensionDialog.addEventListener('click',e=>{if(e.target===dimensionDialog){const r=dimensionDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dimensionDialog.close();}});
function showDimensions(type){
  document.getElementById('dimensions-content').innerHTML=dimensionContent(type);
  dimensionDialog.querySelectorAll('[data-dimension-model]').forEach(b=>b.addEventListener('click',()=>{showDimensions(b.dataset.dimensionModel);dimensionDialog.querySelector(`[data-dimension-model="${b.dataset.dimensionModel}"]`).focus({preventScroll:true});}));
  if(!dimensionDialog.open)dimensionDialog.showModal();dimensionDialog.scrollTop=0;
}
function renderDimensionSummary(type){document.getElementById('dimension-summary').innerHTML=dimensionSummary(type);document.getElementById('dimensions-open').addEventListener('click',()=>showDimensions(type));}
const container=document.getElementById('model-canvas'),scene=new THREE.Scene();scene.background=new THREE.Color(0x17242e);
const renderer=createStableRenderer();renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(34,1,.1,3000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=400;controls.enablePan=true;
const pmrem=new THREE.PMREMGenerator(renderer);const studio=new RoomEnvironment();const environment=pmrem.fromScene(studio,.04);scene.environment=environment.texture;scene.environmentIntensity=.45;pmrem.dispose();studio.dispose();
scene.add(new THREE.HemisphereLight(0xd1e1ee,0x526373,1.6));const sun=new THREE.DirectionalLight(0xffead3,3);sun.position.set(-30,70,55);scene.add(sun);const fill=new THREE.DirectionalLight(0xb8d5ff,1.6);fill.position.set(40,35,-45);scene.add(fill);
const floor=new THREE.GridHelper(120,60,0x526573,0x273b49);floor.position.y=-.71;scene.add(floor);
const inspectionFill=new THREE.DirectionalLight(0xd5e7f7,1.2);inspectionFill.position.set(8,-20,14);scene.add(inspectionFill);
let vehicle,mode='ship',view='front',part;const heights={ship:52,falcon9:47.3,heavy:70,booster:72};
const content={ship:['STARSHIP','四片可动襟翼','两片小型前襟翼向背风侧偏置；两片大型后襟翼从尾裙附近开始。','六边形隔热瓦','瓦片按曲面尺度排列，覆盖迎风侧和相应襟翼表面，鼻尖覆盖范围增加。'],falcon9:['FALCON 9 · FIRST STAGE','四条碳纤维支腿','主腿绕底部铰链向外展开，高位固定点通过多段伸缩支撑杆连接腿端。','展开与收拢','展开足迹约 18 m，脚垫保持接地角度；收拢后贴近箭体。'],heavy:['FALCON HEAVY','三芯结构','整体宽度 12.2 m，中心级和侧芯之间设置连接结构。','同源回收结构','三枚芯级均有四条支腿和四片栅格舵，本页可检查同步展开。'],booster:['SUPER HEAVY','33 台 Raptor','中心 3 台、内圈 10 台、外圈 20 台；上端有热分级环与四片栅格舵。','不锈钢助推器','助推器不铺设星舰飞船的黑色瓦面，尾部增加纵向边条结构。']};
function pose(){const amount=Number(document.getElementById('deploy').value);document.getElementById('deploy-value').textContent=Math.round(amount*100)+'%';if(mode==='ship')setShipFlaps(part,amount*.85);else{for(const p of[vehicle.booster,...vehicle.sides]){setLandingLegs(p,amount);p.fins.forEach(f=>{if(mode!=='booster')f.rotation.x=-Math.PI/2*(1-amount);});}if(mode==='heavy'){vehicle.sides.forEach((p,i)=>p.group.position.x=(i?1:-1)*(vehicle.coreOffset+18*amount));if(vehicle.booster.mounts)vehicle.booster.mounts.visible=amount===0;}}}
function select(type){if(vehicle)disposeVehicle(vehicle);mode=type;vehicle=createVehicle(type==='ship'||type==='booster'?'starship':type);part=type==='ship'?vehicle.upper:vehicle.booster;
  if(type==='heavy'){scene.add(vehicle.booster.group,vehicle.upper.group,...vehicle.sides.map(p=>p.group));vehicle.upper.group.position.y=vehicle.join;vehicle.sides.forEach((p,i)=>p.group.position.x=(i?1:-1)*vehicle.coreOffset);}else scene.add(part.group);
  document.querySelectorAll('[data-model]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.model===mode));const c=content[mode];document.getElementById('model-title').textContent=c[0];document.getElementById('model-notes').innerHTML=`<h3>${c[1]}</h3><p>${c[2]}</p><h3>${c[3]}</h3><p>${c[4]}</p>`;
  renderDimensionSummary(mode);
  prepareSceneDepth(scene,renderer);
  document.getElementById('mechanism-note').textContent=mode==='ship'?'转动四片襟翼，观察铰链与两侧表面。':mode==='booster'?'该型号使用塔架捕获，没有猎鹰式着陆腿。':mode==='heavy'?'展开时拉开芯级间距以便检视；此处为结构展示。':'拖动滑块，观察支腿和伸缩杆同步展开。';document.getElementById('deploy').disabled=mode==='booster';document.getElementById('deploy').value='0';document.getElementById('official-link').href=`https://www.spacex.com/vehicles/${mode==='ship'||mode==='booster'?'starship':mode==='heavy'?'falcon-heavy':'falcon-9'}`;pose();setView(mode==='falcon9'?'detail':'front');}
function setView(next){view=next;const height=heights[mode];let target=new THREE.Vector3(0,height*.48,0),offset=new THREE.Vector3(0,0,height*1.95);floor.visible=next!=='engines';
  if(next==='back')offset.z*=-1;
  if(next==='overall')offset.set(height*.85,height*.22,height*1.9);
  if(next==='detail'){if(mode==='ship'){target.set(0,43,0);offset.set(8,2,26);}else if(mode==='falcon9'||mode==='heavy'){target.set(0,4.4,0);offset.set(18,11,34);}else{target.set(0,67,0);offset.set(17,5,25);}}
  if(next==='engines'){target.set(0,1,0);offset.set(.3,-17,2);if(mode==='heavy')offset.y=-28;}
  controls.target.copy(target);camera.position.copy(target).add(offset);camera.lookAt(target);controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===next));document.getElementById('view-caption').textContent=mode==='ship'?(next==='back'?'裸露不锈钢与襟翼背面的加强结构。':'黑色隔热瓦朝向迎风面，背风面露出不锈钢。'):'使用与发射模拟器相同的模型。';}
document.querySelectorAll('[data-model]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.model)));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.getElementById('deploy').addEventListener('input',pose);
new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(container);
select('ship');function animate(){controls.update();renderer.render(scene,camera);requestAnimationFrame(animate);}animate();
window.modelReview={inspect:()=>{part.group.updateMatrixWorld(true);return{mode,view,flaps:part.fins.map(f=>({name:f.name,position:f.position.toArray(),rotation:f.rotation.toArray().slice(0,3),hingeBase:f.localToWorld(new THREE.Vector3()).toArray(),hingeTip:f.localToWorld(new THREE.Vector3(0,f.userData.length||0,0)).toArray(),mountBase:f.userData.mount?.localToWorld(new THREE.Vector3()).toArray(),mountTip:f.userData.mount?.localToWorld(new THREE.Vector3(0,f.userData.length||0,0)).toArray()})),legs:part.legs.map(l=>({angle:l.rotation.x,foot:l.userData.foot.getWorldPosition(new THREE.Vector3()).toArray(),strutLength:l.userData.tubes.reduce((sum,m)=>sum+m.scale.y-.16,0)})),engines:part.engines.length};}};

